[package]
name = "rust-tui"
version = "0.1.0"
edition = "2021"
authors = ["Michael Hall <michael@rubberduck-labs.com>"]
license = "MIT"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"